### ISSUE TITLE
Disable beeper sound?

### ISSUE THREAD

**Issue by linuxhuskarl** [hsbsbz/M5StickCPlus2-Seamonsue#2]
Hi, first of all: it is such a great app, especially the aesthetics!

Have you considered to add the possibility to toggle sound output?
It could improve the UX a bit, because some people are more sensitive to beeping sounds :)

**Comment by hsbsbz** [comment]
Hi, You are right!
Sound can now be turned off by long press the A button on the home screen.

thank you :D
